language: java
matrix:
  include:
  - language: java
    script:
    - gradle build
    deploy:
      provider: heroku
      api_key:
        secure: v0s5NO04bPeJedpMuHXixJWcyhcZndlE8IY1/yWZtO7GdK14RDJVfiCJB0UpfJK4NuGrvW/JdKyULW+HxM/Y0nxG1MjB8ZwugJTcUOCCYtLG8PVA+qHI2VZ9ua6TyL8jUXkpFuWO2tZJU/HcsropwkSRYYEKGHA5vz3JntrLeoSGtARrtxttTRto4H85sLgs5UTOSy//GXm+ToDuqFrbRc9c6LeGwYTLINJKoKeRA43+jOP3m0EcURM2+4LCdSAng3sF7XbHEhq6qX4r/rcA/RlvXZP5wqh5OAqwyBI2H3QZvvR1cFL27Zoa1LbZ93iyZtA+Hzpl4lP+IRCy0eIk+9Z6tqzAKwZOdeShdIB/UcwmKlTvG4fW4uqTI0elgxTc2kqL834sUK1yzbVwgTqPn08WVmTvsMge/syO6Tho8zLSDQg6OnezhfFRff26s7GheldqasFEnoT36o9cyUi1AzTI8oWzpT2fhW6Is0ExwOP5CRGBWm2n4sI+XJtlVPfFOuZ+nq+ssdG0QsauxX2n27oBGdE69iXVRW/uz1IwlHDmxw/GejUjet0pap5neLg9D/KXsLK3heH283dBM+uMg6PG15L3bYZOl9asi4S5ID4hJQLH9J9VtCnS5rm2BxhIv1fsy+a06CQ5pAlNE/4BVz3Ecs/1M1qCVnn1fNe7AAw=
      app: tutoringsystem-backend
      on:
        repo: McGill-ECSE321-Fall2019/project-group-4
  - language: node_js
    node_js: stable
    before_install: cd tutoringsystem-frontend
    install:
                       - npm install
    script:
    - npm run build
    deploy:
      provider: heroku
      api_key:
        secure: v0s5NO04bPeJedpMuHXixJWcyhcZndlE8IY1/yWZtO7GdK14RDJVfiCJB0UpfJK4NuGrvW/JdKyULW+HxM/Y0nxG1MjB8ZwugJTcUOCCYtLG8PVA+qHI2VZ9ua6TyL8jUXkpFuWO2tZJU/HcsropwkSRYYEKGHA5vz3JntrLeoSGtARrtxttTRto4H85sLgs5UTOSy//GXm+ToDuqFrbRc9c6LeGwYTLINJKoKeRA43+jOP3m0EcURM2+4LCdSAng3sF7XbHEhq6qX4r/rcA/RlvXZP5wqh5OAqwyBI2H3QZvvR1cFL27Zoa1LbZ93iyZtA+Hzpl4lP+IRCy0eIk+9Z6tqzAKwZOdeShdIB/UcwmKlTvG4fW4uqTI0elgxTc2kqL834sUK1yzbVwgTqPn08WVmTvsMge/syO6Tho8zLSDQg6OnezhfFRff26s7GheldqasFEnoT36o9cyUi1AzTI8oWzpT2fhW6Is0ExwOP5CRGBWm2n4sI+XJtlVPfFOuZ+nq+ssdG0QsauxX2n27oBGdE69iXVRW/uz1IwlHDmxw/GejUjet0pap5neLg9D/KXsLK3heH283dBM+uMg6PG15L3bYZOl9asi4S5ID4hJQLH9J9VtCnS5rm2BxhIv1fsy+a06CQ5pAlNE/4BVz3Ecs/1M1qCVnn1fNe7AAw=
      app: tutoringsystem-frontend
      on:
        repo: McGill-ECSE321-Fall2019/project-group-4

