language: java
matrix:
  include:
  - language: java
    script:
    - gradle build
    deploy:
      provider: heroku
      api_key:
        secure:  QOomQh1Df9ZRqy0WvRwVLptB6ARB0Nx2EeCD1mVdqKDOEs/mcm6nmGthyVVlC5kZGT6TG3+uCLjTFT4dylOhQdvZugGzdF7RrMiXsa6o3fxRYkYH0CxmICEDe29ihL4lfysV/ZF3qHiKZv20ObMzJ02VGjylxv4maR4AG4UdI2xCRIIN4xvZIkDz9WOxQWQoeX9LvkogbL3nxqjRP/MRtMUIsT+KjK0n5WAmscY+NvEcz25YlxguphqsDkYjUguSwxfx2ZfQf4f3BvYu++hZbn7ydgcY5mOt9othLyD08YgMZVxDs7IyRHO2Yc/JHzYxckOK4QVYSaSuIinAm1epKigVplT9SxjBDQGLLV4ojp4XC3nIX0U9M+5ckOwjd8OOM5v26hSOS/lRuaaAR1qGjz3y5qTAoJqW1IFIN/iTuRWmamIpiZf5LG/m+QZ2Xp/Vk2Wj0I8XtwSrCaa5mUVLGgv7z4oPs4VZ74k9R4FTkJ1Ms1LaiOcCeG30GMpia7Hp5ImqeQRaQGqkTLy06ikcMqsYx9ysJPcYQEG+yLr3HK+vQmKRnw8wRH+yJBIHGCzeJEU5d8e7bqpfrYhWqVigV5GuWaTpI9vmmQKk3FdzvaEpntkt28rBB0eZdsbbMdEnXMz8B+1MZtbJdPZRUfu2b6sdOXnsf/lI0sjbcVL2rSI=
      app: tutoringsystem-backend
      on:
        repo: McGill-ECSE321-Fall2019/project-group-4
  - language: node_js
    node_js: stable
    before_install: cd tutoringsystem-frontend
    script:
    - npm run build
    deploy:
      provider: heroku
      api_key:
        secure:  QOomQh1Df9ZRqy0WvRwVLptB6ARB0Nx2EeCD1mVdqKDOEs/mcm6nmGthyVVlC5kZGT6TG3+uCLjTFT4dylOhQdvZugGzdF7RrMiXsa6o3fxRYkYH0CxmICEDe29ihL4lfysV/ZF3qHiKZv20ObMzJ02VGjylxv4maR4AG4UdI2xCRIIN4xvZIkDz9WOxQWQoeX9LvkogbL3nxqjRP/MRtMUIsT+KjK0n5WAmscY+NvEcz25YlxguphqsDkYjUguSwxfx2ZfQf4f3BvYu++hZbn7ydgcY5mOt9othLyD08YgMZVxDs7IyRHO2Yc/JHzYxckOK4QVYSaSuIinAm1epKigVplT9SxjBDQGLLV4ojp4XC3nIX0U9M+5ckOwjd8OOM5v26hSOS/lRuaaAR1qGjz3y5qTAoJqW1IFIN/iTuRWmamIpiZf5LG/m+QZ2Xp/Vk2Wj0I8XtwSrCaa5mUVLGgv7z4oPs4VZ74k9R4FTkJ1Ms1LaiOcCeG30GMpia7Hp5ImqeQRaQGqkTLy06ikcMqsYx9ysJPcYQEG+yLr3HK+vQmKRnw8wRH+yJBIHGCzeJEU5d8e7bqpfrYhWqVigV5GuWaTpI9vmmQKk3FdzvaEpntkt28rBB0eZdsbbMdEnXMz8B+1MZtbJdPZRUfu2b6sdOXnsf/lI0sjbcVL2rSI=
      app: tutoringsystem-frontend
      on:
        repo: McGill-ECSE321-Fall2019/project-group-4



