language: java
script:
- gradle build
deploy:
  provider: heroku
  app: tutoringsystem-backend
  api_key:
    secure: "AcnrB7K4sY3SgxeHEeWuM+9Cxf9W2ekPglhK991v6CNWG5ib/3YDBzK0unCDBo9CJWjdA8bZ7Vzh9rOf8YLcAhc5m7S/eWn3jtk8oPxmB3iau+y4Hgu8YsscK7jt4mzOTPiuhok8afrL2gsqJG1iiUWVkOqwwiYY0HpvVfs6xyO2UA272OagUGu6cxRYBtIEqFQn0du3EFUe3E6ONoaFdIY+Au+3R395D1cgxH2tDFCP5cFAwmlhYXe1TE/sH1uBVJwSdLXuRojSMbRM6wgPsd1LxUZwmPlUVAZJX5DyV9jel1qIk4PijNxDwGdrTWP5jGBsq1m12tJeRvXySYra3Bn2m2LukJikjNj92F6SUcc1Ok7E966xul0hlRM0jCsSapzjKGpE6aD3IbPje/H1GiMYTPw/1xQxecxz62RIrhf5x/THOmzNsRdvZbLowhiJPawMSFWIsh9ALk5SyHPT+m45Qo9mxDJ0O1orQWqGhq/72KSvjLTGkIMdxVBzL7wGZgVswqC53H+7PrrgqVmh7/th/X0bf24hy6ZPnXMw+30QqYa4lEJZQnxrl2lC/npGHw8ZlfkvvZDKpj5m8sEWeMBKHkUoOxEbKmV3y81cxhGWqlrVphGnzIm/o61O8OSKPIu4n4WHlNiX1T2+Z0Ulvh1vii/xDh7sHBaOIT9IWo0="
  on:
   repo: McGill-ECSE321-Fall2019/project-group-4
