language: java
matrix:
  include:
  - language: java
    script:
    - gradle build
    deploy:
      provider: heroku
      api_key:
        secure: W3D10J+C8FcnE6ruFIpFgyUHmyTSBZgh35sbwr7MRn+zKvN3C5/jYMvy2MElaEMUitkRQ+dWcr99zgn1g+4SEz7K6lKtfLRCOacYh/1OSLvEU9uYxLO+YcmOWCeHdEIjSBesn7sNAIG9b1G/mWP+ym4++rif1vsxBXHpEl4OaaHSTwU1hPd9+H2UTHyjCysAeskyoLwb8b047fXahoLW92W1vRBwC/8z8493PRiwo2vDePQUerbOi9UMw8EUivbc+Dn2S6ffWmqBxKvHzADsTG/kPTfJMImK8varE5QRgGeRCURnbx1dV4ihrQcwOSNeUptegokup4PkU+ixuxynFnHnZNzgb4cEmgTmNBNPhM4hgKDR+/NPsK8WIcol7zkHH69q4wtiJw6Bo3OVSr0fHU/x6H5zwC05HTELrdmwILkezP1WUMOic1XHKZ/KKeDnqdBBCwr1VSDFfTggIw7k2AXiEw4g9wTBJNoKtjvTSc6GuA6by0zgksUzrPy+aUDvGc5Ro4kPll0Qwv9XYvWQ0LO+zeByzkFJchTJd66aeDkpbG6kbPagMzIqt4ndJvqG6tflXXi8tFDnxyM2LEC40mPH4IfEUiVoVD0imIGmY6eJh0uoqeN6A4+ycfHtd6ZS0Mc/S0Odx+kkKEP6PpHkmWIrqF4aClClKoKBLLXoY+w=
      app: tutoringsystem-backend
      on:
        repo: McGill-ECSE321-Fall2019/project-group-4
  - language: node_js
    node_js: stable
    before_install: cd tutoringsystem-frontend
    install:
    - npm install
    script:
    - npm run build
    deploy:
      provider: heroku
      api_key:
        secure: W3D10J+C8FcnE6ruFIpFgyUHmyTSBZgh35sbwr7MRn+zKvN3C5/jYMvy2MElaEMUitkRQ+dWcr99zgn1g+4SEz7K6lKtfLRCOacYh/1OSLvEU9uYxLO+YcmOWCeHdEIjSBesn7sNAIG9b1G/mWP+ym4++rif1vsxBXHpEl4OaaHSTwU1hPd9+H2UTHyjCysAeskyoLwb8b047fXahoLW92W1vRBwC/8z8493PRiwo2vDePQUerbOi9UMw8EUivbc+Dn2S6ffWmqBxKvHzADsTG/kPTfJMImK8varE5QRgGeRCURnbx1dV4ihrQcwOSNeUptegokup4PkU+ixuxynFnHnZNzgb4cEmgTmNBNPhM4hgKDR+/NPsK8WIcol7zkHH69q4wtiJw6Bo3OVSr0fHU/x6H5zwC05HTELrdmwILkezP1WUMOic1XHKZ/KKeDnqdBBCwr1VSDFfTggIw7k2AXiEw4g9wTBJNoKtjvTSc6GuA6by0zgksUzrPy+aUDvGc5Ro4kPll0Qwv9XYvWQ0LO+zeByzkFJchTJd66aeDkpbG6kbPagMzIqt4ndJvqG6tflXXi8tFDnxyM2LEC40mPH4IfEUiVoVD0imIGmY6eJh0uoqeN6A4+ycfHtd6ZS0Mc/S0Odx+kkKEP6PpHkmWIrqF4aClClKoKBLLXoY+w=
      app: tutoringsystem-frontend
      on:
        repo: McGill-ECSE321-Fall2019/project-group-4
